### ISSUE TITLE
Batch Buying

### ISSUE THREAD

**Issue by Candcg** [MrBacon470/Chemcremental-JS#17]
Changing the batch setting, or buy multiple does not change the listed price of a purchase, so you don't know if you have enough, and if you don't it will buy as many as it can. This is not an acceptable standard. Either have the prices change to reflect the current multiplier (e.g. at 'buy 10' the price will display as the sum of the costs 1 to 10), or add a 'buy max' multiplier and don't allow partial batch buying

**Comment by VoidCloud04** [comment]
This is a matter of complexity if I could implement a buy max I would but this is out of the realm of my skillset I've tried and failed to implement buy maxes which is why I choose multiples. As for considering this an "unacceptable standard" is just quite frankly irritating to me because the way this works is the same way it is in synergism which does not update costs according to buy amounts along with purchasing as many as it can if it can do the full thing.

So nonetheless for the time being this will remain this way due to skillset constraints and personal choice.
Thank you for opening this none the less.
